/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TypesSchema = DividendsUpcomingQuery | DividendsUpcomingItem | DividendsUpcomingResponse | Target;
export type Target = "yahoo";

export interface DividendsUpcomingQuery {
  symbol: string[];
  target: Target;
}
export interface DividendsUpcomingItem {
  ex_div_date: string | null;
  payment_date: string | null;
  dps: number | null;
  annual_dps: number | null;
  are_dates_estimated: boolean;
}
export interface DividendsUpcomingResponse {
  data: {
    [k: string]: DividendsUpcomingItem;
  };
  errors: {
    [k: string]: string;
  };
}
