"""Generate the Python types package from shared and poller model files.

Produces two standalone modules inside types/python/ibkr_relay_types/:
  - shared.py — public types from services/shared/models.py
  - poller.py — poller-specific types from services/poller/poller_models.py
                 (imports rewritten from ``shared`` to ``.shared``)

Usage: python gen_python_types.py
"""

import pathlib
import re
import sys

SHARED_SRC = pathlib.Path("services/shared/models.py")
POLLER_SRC = pathlib.Path("services/poller/poller_models.py")
OUT_DIR = pathlib.Path("types/python/ibkr_relay_types")

SHARED_HEADER = '''\
"""ibkr-relay shared types — CommonFill models and type aliases.

AUTO-GENERATED by gen_python_types.py from services/shared/models.py.
Do not edit manually — run ``make types`` to regenerate.
"""
'''

POLLER_HEADER = '''\
"""ibkr-relay poller types — poller-specific API models.

AUTO-GENERATED by gen_python_types.py from services/poller/poller_models.py.
Do not edit manually — run ``make types`` to regenerate.
"""
'''


def _strip_docstring(source: str) -> str:
    """Remove the module-level docstring."""
    if source.startswith('"""'):
        closing = source.find('"""', 3)
        if closing != -1:
            return source[closing + 3:].lstrip("\n")
    return source


def _rewrite_poller_imports(source: str) -> str:
    """Rewrite ``from shared import X`` to ``from .shared import X``."""
    return re.sub(r"^from shared import ", "from .shared import ", source, flags=re.MULTILINE)


def generate_shared() -> None:
    """Generate shared.py by copying models.py (strip docstring + SCHEMA_MODELS)."""
    if not SHARED_SRC.exists():
        print(f"ERROR: {SHARED_SRC} not found", file=sys.stderr)
        sys.exit(1)

    source = SHARED_SRC.read_text()
    body = _strip_docstring(source)

    out = OUT_DIR / "shared.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(SHARED_HEADER + "\n" + body)
    print(f"Generated {out}")


def generate_poller() -> None:
    """Generate poller.py from poller_models.py with rewritten imports."""
    if not POLLER_SRC.exists():
        print(f"ERROR: {POLLER_SRC} not found", file=sys.stderr)
        sys.exit(1)

    source = POLLER_SRC.read_text()
    body = _strip_docstring(source)
    body = _rewrite_poller_imports(body)

    out = OUT_DIR / "poller.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(POLLER_HEADER + "\n" + body)
    print(f"Generated {out}")


if __name__ == "__main__":
    generate_shared()
    generate_poller()
