"""Generate the Python types package from shared and relay model files.

Mirrors the relay_core source structure into types/python/b_relay_types/:

  Source                                  Generated
  ──────────────────────────────────────  ─────────────────────────────────────
  services/shared/models.py            →  b_relay_types/shared.py
  services/relay_core/relay_models.py  →  b_relay_types/relay_api.py
  relay_core/notifier/models.py        →  b_relay_types/notifier/models.py

Each file is copied verbatim (docstring stripped, header prepended) with one
import rewrite to fix the relative depth:

  shared.py          : from shared import  →  from .shared import
  relay_api.py       : from shared import  →  from .shared import
                       from .notifier …    →  (unchanged — path stays valid)
  notifier/models.py : from shared import  →  from ..shared import

Usage: python gen_python_types.py
"""

import pathlib
import re
import sys

SHARED_SRC = pathlib.Path("services/shared/models.py")
RELAY_API_SRC = pathlib.Path("services/relay_core/relay_models.py")
NOTIFIER_MODELS_SRC = pathlib.Path("services/relay_core/notifier/models.py")
OUT_DIR = pathlib.Path("types/python/b_relay_types")

# Public symbols re-exported from the top-level __init__.py barrel.
# Must be kept in sync with the source models manually.
SHARED_EXPORTS = ["AssetClass", "BuySell", "Fill", "OrderType", "Source", "Trade"]
NOTIFIER_EXPORTS = ["WebhookPayload", "WebhookPayloadTrades"]
RELAY_API_EXPORTS = ["HealthResponse", "RunPollResponse"]

SHARED_HEADER = '''\
"""b_relay_types shared types — CommonFill models and type aliases.

AUTO-GENERATED by gen_python_types.py from services/shared/models.py.
Do not edit manually — run ``make types`` to regenerate.
"""
'''

RELAY_API_HEADER = '''\
"""b_relay_types relay API response models.

AUTO-GENERATED by gen_python_types.py from services/relay_core/relay_models.py.
Do not edit manually — run ``make types`` to regenerate.
"""
'''

NOTIFIER_MODELS_HEADER = '''\
"""b_relay_types notifier payload contracts.

AUTO-GENERATED by gen_python_types.py from services/relay_core/notifier/models.py.
Do not edit manually — run ``make types`` to regenerate.
"""
'''

INIT_HEADER = '''\
"""b_relay_types — Pydantic models for Broker Relay.

Mirrors the relay_core source structure:
  - shared             : CommonFill primitives (Fill, Trade, BuySell, …)
  - notifier.models    : Outbound payload contracts (WebhookPayloadTrades, …)
  - relay_api          : Relay route response models (RunPollResponse, …)

Run ``make types`` to regenerate.
"""
'''


def _strip_docstring(source: str) -> str:
    if source.startswith('"""'):
        end = source.find('"""', 3)
        if end != -1:
            return source[end + 3:].lstrip("\n")
    return source


def _rewrite(source: str, pattern: str, replacement: str) -> str:
    return re.sub(pattern, replacement, source, flags=re.MULTILINE)


def _copy(src: pathlib.Path, out: pathlib.Path, header: str, rewrites: list[tuple[str, str]]) -> None:
    if not src.exists():
        print(f"ERROR: {src} not found", file=sys.stderr)
        sys.exit(1)
    body = _strip_docstring(src.read_text())
    for pattern, replacement in rewrites:
        body = _rewrite(body, pattern, replacement)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(header + "\n" + body)
    print(f"Generated {out}")


def generate_shared() -> None:
    _copy(
        SHARED_SRC,
        OUT_DIR / "shared.py",
        SHARED_HEADER,
        [(r"^from shared import ", "from .shared import ")],
    )


def generate_relay_api() -> None:
    _copy(
        RELAY_API_SRC,
        OUT_DIR / "relay_api.py",
        RELAY_API_HEADER,
        [
            # RelayName is only imported in the source for schema_gen hoisting;
            # it is unused in the types package. Strip it so the generated file
            # stays lint-clean without needing a noqa suppression.
            (r"^from shared import RelayName, Trade.*\n", "from shared import Trade\n"),
            (r"^from shared import ", "from .shared import "),
            # from .notifier.models import … is unchanged — it resolves correctly
            # in the mirrored package structure.
        ],
    )


def generate_notifier_models() -> None:
    _copy(
        NOTIFIER_MODELS_SRC,
        OUT_DIR / "notifier" / "models.py",
        NOTIFIER_MODELS_HEADER,
        [(r"^from shared import ", "from ..shared import ")],
    )


def generate_notifier_init() -> None:
    out = OUT_DIR / "notifier" / "__init__.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("")
    print(f"Generated {out}")


def generate_init() -> None:
    lines = [INIT_HEADER]
    for symbol in NOTIFIER_EXPORTS:
        lines.append(f"from .notifier.models import {symbol} as {symbol}")
    for symbol in RELAY_API_EXPORTS:
        lines.append(f"from .relay_api import {symbol} as {symbol}")
    for symbol in SHARED_EXPORTS:
        lines.append(f"from .shared import {symbol} as {symbol}")
    lines.append("")
    out = OUT_DIR / "__init__.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated {out}")


if __name__ == "__main__":
    generate_shared()
    generate_relay_api()
    generate_notifier_models()
    generate_notifier_init()
    generate_init()
