"""Generate ``index.d.ts`` barrels for TypeScript modules.

Walks each ``types/typescript/<module>/types.d.ts`` looking for top-level
``export type`` / ``export interface`` declarations and writes a sibling
``index.d.ts`` re-exporting all of them.

Run after ``schema_gen.py`` + ``json-schema-to-typescript`` have produced
``types.d.ts``. Invoked from ``make types``.

Usage: python gen_ts_barrels.py
"""

import pathlib
import re
import sys

# Modules to (re)generate, in **precedence order**. Each entry is a
# directory under ``types/typescript/`` that contains an auto-generated
# ``types.d.ts``.
#
# Precedence semantics: when a name appears in multiple modules'
# ``types.d.ts`` (which happens because ``json-schema-to-typescript``
# inlines transitively-referenced types into every output file), the
# barrel of the **earlier** module owns the public re-export. Later
# modules' barrels skip the duplicate.
#
# This restores the architectural split — ``shared`` is the canonical
# home for cross-relay primitives (Fill, Trade, BuySell), ``relay_api``
# is the home for relay-specific endpoint shapes — without forcing
# schema_gen.py to emit cross-file ``$ref``s.
TS_MODULES = ["shared", "relay_api"]

TS_BASE = pathlib.Path("types/typescript")

HEADER = (
    "// AUTO-GENERATED by gen_ts_barrels.py — do not edit manually.\n"
    "// Run `make types` to regenerate.\n"
    "\n"
)

# Match top-level ``export type Foo`` and ``export interface Foo`` lines.
# Skip generic / parameterised exports just in case (we don't use them).
_DECL_RE = re.compile(r"^export\s+(?:type|interface)\s+([A-Za-z_][A-Za-z0-9_]*)\b")

# Synthetic names we never want in the barrel (e.g. the umbrella TypesSchema
# emitted by json-schema-to-typescript when given a top-level anyOf).
_BARREL_SKIP = {"TypesSchema"}


def _collect_exports(types_dts: pathlib.Path) -> list[str]:
    """Return alphabetically sorted public type/interface names from *types_dts*."""
    if not types_dts.exists():
        print(f"ERROR: {types_dts} not found — run `make types` first", file=sys.stderr)
        sys.exit(1)
    names: set[str] = set()
    for line in types_dts.read_text().splitlines():
        m = _DECL_RE.match(line)
        if m and m.group(1) not in _BARREL_SKIP:
            names.add(m.group(1))
    return sorted(names)


def _render_barrel(names: list[str]) -> str:
    body = ["export type {"]
    body.extend(f"  {n}," for n in names)
    body.append('} from "./types";')
    body.append("")
    return HEADER + "\n".join(body)


def main() -> None:
    # Names already claimed by an earlier module's barrel — skipped in
    # later modules to avoid duplicate public re-exports.
    claimed: set[str] = set()
    for module in TS_MODULES:
        module_dir = TS_BASE / module
        types_dts = module_dir / "types.d.ts"
        all_names = _collect_exports(types_dts)
        if not all_names:
            raise SystemExit(
                f"ERROR: no exported types found in {types_dts}",
            )
        names = [n for n in all_names if n not in claimed]
        skipped = sorted(set(all_names) - set(names))
        index_dts = module_dir / "index.d.ts"
        index_dts.write_text(_render_barrel(names))
        suffix = (
            f" — skipped {len(skipped)} duplicate(s) owned by an earlier"
            f" module: {', '.join(skipped)}"
            if skipped
            else ""
        )
        print(f"Generated {index_dts} ({len(names)} exports){suffix}")
        claimed.update(names)


if __name__ == "__main__":
    main()
