"""Generate the Python types package from shared and relay model files.

Produces two standalone modules inside types/python/broker_relay_types/:
  - shared.py    — public types from services/shared/models.py
  - relay_api.py — relay API types from services/relay_core/relay_models.py
                   (imports rewritten from ``shared`` to ``.shared``)

Usage: python gen_python_types.py
"""

import pathlib
import re
import sys

SHARED_SRC = pathlib.Path("services/shared/models.py")
RELAY_API_SRC = pathlib.Path("services/relay_core/relay_models.py")
OUT_DIR = pathlib.Path("types/python/broker_relay_types")

SHARED_HEADER = '''\
"""broker-relay shared types — CommonFill models and type aliases.

AUTO-GENERATED by gen_python_types.py from services/shared/models.py.
Do not edit manually — run ``make types`` to regenerate.
"""
'''

RELAY_API_HEADER = '''\
"""broker-relay API types — relay route response models.

AUTO-GENERATED by gen_python_types.py from services/relay_core/relay_models.py.
Do not edit manually — run ``make types`` to regenerate.
"""
'''


def _strip_docstring(source: str) -> str:
    """Remove the module-level docstring."""
    if source.startswith('"""'):
        closing = source.find('"""', 3)
        if closing != -1:
            return source[closing + 3:].lstrip("\n")
    return source


def _rewrite_relay_imports(source: str) -> str:
    """Rewrite ``from shared import X`` to ``from .shared import X``."""
    return re.sub(r"^from shared import ", "from .shared import ", source, flags=re.MULTILINE)


def generate_shared() -> None:
    """Generate shared.py by copying models.py (strip docstring + SCHEMA_MODELS)."""
    if not SHARED_SRC.exists():
        print(f"ERROR: {SHARED_SRC} not found", file=sys.stderr)
        sys.exit(1)

    source = SHARED_SRC.read_text()
    body = _strip_docstring(source)

    out = OUT_DIR / "shared.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(SHARED_HEADER + "\n" + body)
    print(f"Generated {out}")


def generate_relay_api() -> None:
    """Generate relay_api.py from relay_models.py with rewritten imports."""
    if not RELAY_API_SRC.exists():
        print(f"ERROR: {RELAY_API_SRC} not found", file=sys.stderr)
        sys.exit(1)

    source = RELAY_API_SRC.read_text()
    body = _strip_docstring(source)
    body = _rewrite_relay_imports(body)

    out = OUT_DIR / "relay_api.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(RELAY_API_HEADER + "\n" + body)
    print(f"Generated {out}")


if __name__ == "__main__":
    generate_shared()
    generate_relay_api()
