"""relayport_types market data API request/response models.

AUTO-GENERATED by gen_python_types.py from services/market_data/models/dividends.py.
Do not edit manually — run ``make types`` to regenerate.
"""

from typing import Literal

from pydantic import BaseModel, ConfigDict, field_validator

Target = Literal["yahoo"]


class DividendsUpcomingQuery(BaseModel):
    model_config = ConfigDict(extra="forbid")

    symbol: list[str]
    target: Target

    @field_validator("symbol", mode="before")
    @classmethod
    def parse_symbol(cls, v: object) -> list[str]:
        if isinstance(v, str):
            return [s.strip().upper() for s in v.split(",") if s.strip()]
        if isinstance(v, list):
            return [str(s).strip().upper() for s in v if str(s).strip()]
        raise ValueError("symbol must be a comma-separated string or list")

    @field_validator("target", mode="before")
    @classmethod
    def validate_target(cls, v: object) -> object:
        if isinstance(v, str):
            return v.strip().lower()
        return v


class DividendsUpcomingItem(BaseModel):
    model_config = ConfigDict(extra="forbid")

    ex_div_date: str | None
    payment_date: str | None
    dps: float | None
    annual_dps: float | None
    are_dates_estimated: bool


class TickerError(BaseModel):
    model_config = ConfigDict(extra="forbid")

    code: str
    message: str


class DividendsUpcomingResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    data: dict[str, DividendsUpcomingItem]
    errors: dict[str, TickerError]
