"""relayport_types shared types — CommonFill models and type aliases.

AUTO-GENERATED by gen_python_types.py from services/shared/models.py.
Do not edit manually — run ``make types`` to regenerate.
"""

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict

RelayName = Literal["ibkr", "kraken"]
"""Allowed relay identifiers — single source of truth.

Used to validate RELAYS env var, discriminate webhook payloads, and
namespace dedup/metadata DB keys. Add new brokers here.
"""

AssetClass = Literal["equity", "option", "crypto", "future", "forex", "other"]

OrderType = Literal["market", "limit", "stop", "stop_limit", "trailing_stop"]


class BuySell(str, Enum):
    BUY = "buy"
    SELL = "sell"


Source = Literal[
    "flex", "execDetailsEvent", "commissionReportEvent",  # IBKR
    "rest_poll", "ws_execution",                           # Kraken
]


FxRateSource = Literal["historical", "latest"]


def _all_fields_required(schema: dict[str, Any]) -> None:
    """Mark every declared field as required in JSON Schema.

    Pydantic's default JSON serialization always emits keys (``None`` →
    ``null``, never omitted), so optional fields on the wire are always
    present. Without this hook, json-schema-to-typescript generates
    ``field?: T | null`` — implying the key may be missing — which
    doesn't match the actual payload. This hook forces the tighter
    ``field: T | null``.
    """
    properties = schema.get("properties", {})
    schema["required"] = list(properties.keys())


class OptionContract(BaseModel):
    """Option-specific contract metadata.

    Populated only on fills/trades whose ``assetClass == "option"``. Future
    derivatives (futures, FOPs, warrants) will get their own sibling
    contract objects rather than reusing this one — see
    ``docs/migrate-trade-models-to-discriminated-union.md`` for the planned
    discriminated-union evolution.
    """

    model_config = ConfigDict(
        extra="forbid", json_schema_extra=_all_fields_required,
    )

    # Underlying ticker (e.g. "AVGO" for an AVGO option).
    rootSymbol: str
    strike: float
    # Last trading day in canonical ISO ``YYYY-MM-DD`` form (e.g. "2026-05-08").
    expiryDate: str
    type: Literal["call", "put"]


class Fill(BaseModel):
    """Individual execution from a broker (CommonFill spec)."""

    model_config = ConfigDict(
        extra="forbid", json_schema_extra=_all_fields_required,
    )

    execId: str
    orderId: str
    symbol: str
    assetClass: AssetClass
    side: BuySell
    orderType: OrderType | None = None
    price: float
    volume: float
    cost: float
    fee: float
    timestamp: str
    source: Source
    # ISO-4217 code of the asset traded (e.g. "USD" for AAPL). None when the
    # broker does not expose an unambiguous fiat currency for the fill (e.g.
    # crypto-quoted-in-crypto pairs like ETH/BTC).
    currency: str | None = None
    # Option-contract metadata. Populated when ``assetClass == "option"``,
    # None for every other asset class. Cross-field consistency (option
    # populated iff assetClass == "option") is enforced by the producing
    # parsers, not by the model itself — see migration plan in docs/.
    option: OptionContract | None = None
    raw: dict[str, Any]


class Trade(BaseModel):
    """Aggregated trade (one or more fills for the same order)."""

    model_config = ConfigDict(
        extra="forbid", json_schema_extra=_all_fields_required,
    )

    orderId: str
    symbol: str
    assetClass: AssetClass
    side: BuySell
    orderType: OrderType | None = None
    price: float
    volume: float
    cost: float
    fee: float
    fillCount: int
    execIds: list[str]
    timestamp: str
    source: Source
    # Copied from the last fill — ISO-4217 or None (see Fill.currency).
    currency: str | None = None
    # Copied from the last fill — option contract metadata for option
    # trades, None for every other asset class (see Fill.option).
    option: OptionContract | None = None
    # Units of fxRateBase per 1 unit of currency, such that
    # cost * fxRate == cost_in_base_currency. Populated by the FX
    # enrichment layer when FX_RATES_ENABLED=true and currency is known.
    fxRate: float | None = None
    fxRateBase: str | None = None
    fxRateSource: FxRateSource | None = None
    raw: dict[str, Any]
