"""relayport_types market data utility: utils.

AUTO-GENERATED by gen_python_types.py from services/market_data/utils.py.
Do not edit manually — run ``make types`` to regenerate.
"""

def parse_string_list(v: object, *, max_count: int | None = None) -> list[str]:
    """Parse a comma-separated string or list into a deduplicated, uppercased list."""
    if isinstance(v, str):
        items = [s.strip().upper() for s in v.split(",") if s.strip()]
    elif isinstance(v, list):
        items = [
            part.strip().upper()
            for s in v
            for part in str(s).split(",")
            if part.strip()
        ]
    else:
        raise ValueError("must be a comma-separated string or list")
    if not items:
        raise ValueError("must contain at least one non-empty value")
    items = list(dict.fromkeys(items))
    if max_count is not None and len(items) > max_count:
        raise ValueError(f"list exceeds maximum of {max_count} items")
    return items
