"""b_relay_types shared types — CommonFill models and type aliases.

AUTO-GENERATED by gen_python_types.py from services/shared/models.py.
Do not edit manually — run ``make types`` to regenerate.
"""

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict

RelayName = Literal["ibkr", "kraken"]
"""Allowed relay identifiers — single source of truth.

Used to validate RELAYS env var, discriminate webhook payloads, and
namespace dedup/metadata DB keys. Add new brokers here.
"""

AssetClass = Literal["equity", "option", "crypto", "future", "forex", "other"]

OrderType = Literal["market", "limit", "stop", "stop_limit", "trailing_stop"]


class BuySell(str, Enum):
    BUY = "buy"
    SELL = "sell"


Source = Literal[
    "flex", "execDetailsEvent", "commissionReportEvent",  # IBKR
    "rest_poll", "ws_execution",                           # Kraken
]


class Fill(BaseModel):
    """Individual execution from a broker (CommonFill spec)."""

    model_config = ConfigDict(extra="forbid")

    execId: str
    orderId: str
    symbol: str
    assetClass: AssetClass
    side: BuySell
    orderType: OrderType | None = None
    price: float
    volume: float
    cost: float
    fee: float
    timestamp: str
    source: Source
    raw: dict[str, Any]


class Trade(BaseModel):
    """Aggregated trade (one or more fills for the same order)."""

    model_config = ConfigDict(extra="forbid")

    orderId: str
    symbol: str
    assetClass: AssetClass
    side: BuySell
    orderType: OrderType | None = None
    price: float
    volume: float
    cost: float
    fee: float
    fillCount: int
    execIds: list[str]
    timestamp: str
    source: Source
    raw: dict[str, Any]
