/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TypesSchema = RunPollResponse | HealthResponse;
export type BuySell = "buy" | "sell";

export interface RunPollResponse {
  trades: Trade[];
}
/**
 * Aggregated trade (one or more fills for the same order).
 */
export interface Trade {
  orderId: string;
  symbol: string;
  assetClass: "equity" | "option" | "crypto" | "future" | "forex" | "other";
  side: BuySell;
  orderType?: ("market" | "limit" | "stop" | "stop_limit" | "trailing_stop") | null;
  price: number;
  volume: number;
  cost: number;
  fee: number;
  fillCount: number;
  execIds: string[];
  timestamp: string;
  source: "flex" | "execDetailsEvent" | "commissionReportEvent";
  raw: {
    [k: string]: unknown;
  };
}
export interface HealthResponse {
  status: string;
}
