/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TypesSchema = WebhookPayloadTrades | RunPollResponse | HealthResponse;
export type RelayName = "ibkr" | "kraken";
export type BuySell = "buy" | "sell";

/**
 * Webhook payload for trade execution events.
 */
export interface WebhookPayloadTrades {
  relay: RelayName;
  type: "trades";
  data: Trade[];
  errors: string[];
}
/**
 * Aggregated trade (one or more fills for the same order).
 */
export interface Trade {
  orderId: string;
  symbol: string;
  assetClass: "equity" | "option" | "crypto" | "future" | "forex" | "other";
  side: BuySell;
  orderType: ("market" | "limit" | "stop" | "stop_limit" | "trailing_stop") | null;
  price: number;
  volume: number;
  cost: number;
  fee: number;
  fillCount: number;
  execIds: string[];
  timestamp: string;
  source: "flex" | "execDetailsEvent" | "commissionReportEvent" | "rest_poll" | "ws_execution";
  currency: string | null;
  option: OptionContract | null;
  fxRate: number | null;
  fxRateBase: string | null;
  fxRateSource: ("historical" | "latest") | null;
  raw: {
    [k: string]: unknown;
  };
}
/**
 * Option-specific contract metadata.
 *
 * Populated only on fills/trades whose ``assetClass == "option"``. Future
 * derivatives (futures, FOPs, warrants) will get their own sibling
 * contract objects rather than reusing this one — see
 * ``docs/migrate-trade-models-to-discriminated-union.md`` for the planned
 * discriminated-union evolution.
 */
export interface OptionContract {
  rootSymbol: string;
  strike: number;
  expiryDate: string;
  type: "call" | "put";
}
export interface RunPollResponse {
  trades: Trade[];
}
export interface HealthResponse {
  status: string;
}
