"""ibkr-relay poller types — poller-specific API models.

AUTO-GENERATED by gen_python_types.py from services/poller/poller_models.py.
Do not edit manually — run ``make types`` to regenerate.
"""

from pydantic import BaseModel, ConfigDict

from .shared import AssetClass as AssetClass
from .shared import BuySell as BuySell
from .shared import Fill as Fill
from .shared import OrderType as OrderType
from .shared import Source as Source
from .shared import Trade as Trade
from .shared import WebhookPayloadTrades as WebhookPayloadTrades

# ── POST /ibkr/poller/run ────────────────────────────────────────────

class RunPollResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    trades: list[Trade]


# ── GET /health ──────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    status: str


# ── Schema export (used by schema_gen.py → make types) ──────────────

