"""ibkr-relay shared types — CommonFill models and type aliases.

AUTO-GENERATED by gen_python_types.py from services/shared/models.py.
Do not edit manually — run ``make types`` to regenerate.
"""

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict

AssetClass = Literal["equity", "option", "crypto", "future", "forex", "other"]

OrderType = Literal["market", "limit", "stop", "stop_limit", "trailing_stop"]


class BuySell(str, Enum):
    BUY = "buy"
    SELL = "sell"


Source = Literal["flex", "execDetailsEvent", "commissionReportEvent"]


class Fill(BaseModel):
    """Individual execution from IBKR (CommonFill spec)."""

    model_config = ConfigDict(extra="forbid")

    execId: str
    orderId: str
    symbol: str
    assetClass: AssetClass
    side: BuySell
    orderType: OrderType | None = None
    price: float
    volume: float
    cost: float
    fee: float
    timestamp: str
    source: Source
    raw: dict[str, Any]


class Trade(BaseModel):
    """Aggregated trade (one or more fills for the same order)."""

    model_config = ConfigDict(extra="forbid")

    orderId: str
    symbol: str
    assetClass: AssetClass
    side: BuySell
    orderType: OrderType | None = None
    price: float
    volume: float
    cost: float
    fee: float
    fillCount: int
    execIds: list[str]
    timestamp: str
    source: Source
    raw: dict[str, Any]


def _require_discriminators(schema: dict[str, Any]) -> None:
    """Keep discriminator fields required in JSON Schema despite defaults."""
    req: list[str] = schema.get("required", [])
    for f in ("relay", "type"):
        if f not in req:
            req.append(f)
    schema["required"] = req


class WebhookPayloadTrades(BaseModel):
    """Webhook payload for trade execution events."""

    model_config = ConfigDict(extra="forbid", json_schema_extra=_require_discriminators)

    relay: Literal["ibkr"] = "ibkr"
    type: Literal["trades"] = "trades"
    data: list[Trade]
    errors: list[str]

# Backward-compatible top-level alias kept for existing imports and the
# intended discriminated-union API. Today there is only one webhook payload
# variant, so the alias points directly to the trades payload model.
WebhookPayload = WebhookPayloadTrades

