"""broker-relay API types — relay route response models.

AUTO-GENERATED by gen_python_types.py from services/relay_core/relay_models.py.
Do not edit manually — run ``make types`` to regenerate.
"""

from pydantic import BaseModel, ConfigDict

from .shared import Trade

# ── POST /relays/{relay_name}/poll/{poll_idx} ────────────────────────

class RunPollResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    trades: list[Trade]


# ── GET /health ──────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    status: str
