/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TypesSchema = PlaceOrderPayload | PlaceOrderResponse | HealthResponse | ListTradesResponse;

/**
 * Top-level request body for POST /ibkr/order.
 */
export interface PlaceOrderPayload {
  contract: ContractPayload;
  order: OrderPayload;
}
/**
 * Contract fields for identifying the instrument (mirrors ib_async.Contract).
 */
export interface ContractPayload {
  symbol: string;
  secType?:
    | "STK"
    | "OPT"
    | "FUT"
    | "IND"
    | "FOP"
    | "CASH"
    | "CFD"
    | "BAG"
    | "WAR"
    | "BOND"
    | "CMDTY"
    | "NEWS"
    | "FUND"
    | "CRYPTO"
    | "EVENT";
  exchange?: string;
  currency?: string;
  primaryExchange?: string;
}
/**
 * Order fields for specifying the trade (mirrors ib_async.Order).
 */
export interface OrderPayload {
  action: "BUY" | "SELL";
  totalQuantity: number;
  orderType: "MKT" | "LMT";
  lmtPrice?: number | null;
  tif?: "DAY" | "GTC" | "IOC" | "GTD" | "OPG" | "FOK" | "DTC";
  outsideRth?: boolean;
}
export interface PlaceOrderResponse {
  status: string;
  orderId: number;
  permId: number;
  action: "BUY" | "SELL";
  symbol: string;
  totalQuantity: number;
  orderType: "MKT" | "LMT";
  lmtPrice?: number | null;
}
export interface HealthResponse {
  connected: boolean;
  tradingMode: string;
}
export interface ListTradesResponse {
  trades: TradeDetail[];
}
/**
 * A trade with its order info, status, and fills.
 */
export interface TradeDetail {
  orderId: number;
  permId: number;
  action: string;
  totalQuantity: number;
  orderType: string;
  lmtPrice?: number | null;
  tif: "DAY" | "GTC" | "IOC" | "GTD" | "OPG" | "FOK" | "DTC";
  symbol: string;
  secType:
    | "STK"
    | "OPT"
    | "FUT"
    | "IND"
    | "FOP"
    | "CASH"
    | "CFD"
    | "BAG"
    | "WAR"
    | "BOND"
    | "CMDTY"
    | "NEWS"
    | "FUND"
    | "CRYPTO"
    | "EVENT";
  exchange: string;
  currency: string;
  status: string;
  filled: number;
  remaining: number;
  avgFillPrice: number;
  fills: FillDetail[];
}
/**
 * Single execution fill within a trade.
 */
export interface FillDetail {
  execId: string;
  time: string;
  exchange: string;
  side: string;
  shares: number;
  price: number;
  commission: number;
  commissionCurrency: string;
  realizedPNL: number;
}
