/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TypesSchema = WebhookPayload | Trade | Fill;
export type BuySell = "buy" | "sell";

/**
 * Payload sent to the target webhook URL.
 */
export interface WebhookPayload {
  trades: Trade[];
  errors: string[];
}
/**
 * Aggregated trade (one or more fills for the same order).
 */
export interface Trade {
  orderId: string;
  symbol: string;
  side: BuySell;
  orderType?: ("market" | "limit" | "stop" | "stop_limit" | "trailing_stop") | null;
  price: number;
  volume: number;
  cost: number;
  fee: number;
  fillCount: number;
  execIds: string[];
  timestamp: string;
  source: "flex" | "execDetailsEvent" | "commissionReportEvent";
  raw: {
    [k: string]: unknown;
  };
}
/**
 * Individual execution from IBKR (CommonFill spec).
 */
export interface Fill {
  execId: string;
  orderId: string;
  symbol: string;
  side: BuySell;
  orderType?: ("market" | "limit" | "stop" | "stop_limit" | "trailing_stop") | null;
  price: number;
  volume: number;
  cost: number;
  fee: number;
  timestamp: string;
  source: "flex" | "execDetailsEvent" | "commissionReportEvent";
  raw: {
    [k: string]: unknown;
  };
}
