/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TypesSchema = Trade | Fill;
export type AssetClass = "crypto" | "equity" | "forex" | "future" | "option" | "other";
export type BuySell = "buy" | "sell";
export type OrderType = "limit" | "market" | "stop" | "stop_limit" | "trailing_stop";
export type Source = "commissionReportEvent" | "execDetailsEvent" | "flex" | "rest_poll" | "ws_execution";
export type FxRateSource = "historical" | "latest";

/**
 * Aggregated trade (one or more fills for the same order).
 */
export interface Trade {
  orderId: string;
  symbol: string;
  assetClass: AssetClass;
  side: BuySell;
  orderType: OrderType | null;
  price: number;
  volume: number;
  cost: number;
  fee: number;
  fillCount: number;
  execIds: string[];
  timestamp: string;
  source: Source;
  currency: string | null;
  rootSymbol: string | null;
  fxRate: number | null;
  fxRateBase: string | null;
  fxRateSource: FxRateSource | null;
  raw: {
    [k: string]: unknown;
  };
}
/**
 * Individual execution from a broker (CommonFill spec).
 */
export interface Fill {
  execId: string;
  orderId: string;
  symbol: string;
  assetClass: AssetClass;
  side: BuySell;
  orderType: OrderType | null;
  price: number;
  volume: number;
  cost: number;
  fee: number;
  timestamp: string;
  source: Source;
  currency: string | null;
  rootSymbol: string | null;
  raw: {
    [k: string]: unknown;
  };
}
